baseurl = "https://tolledo23.dev"
title = "Constantine Gerasimovich"
theme = "hugo-coder"
languagecode = "en"
defaultcontentlanguage = "en"

paginate = 20

disqusShortname = "tolledo23.dev"

[markup.highlight]
style = "github-dark"

[params]
  author = "Constantine Gerasimovich"
  info = "Software Engineer"
  description = "Constantine Gerasimovoch's personal website"
  keywords = "blog,developer,personal"
  avatarurl = "images/avatar.jpg"
  #gravatar = "john.doe@example.com"

  faviconSVG = "/img/favicon.svg"
  favicon_32 = "/img/favicon-32x32.png"
  favicon_16 = "/img/favicon-16x16.png"

  since = 2023

  enableTwemoji = true

  colorScheme = "auto"
  hidecolorschemetoggle = false

  # customCSS = ["css/custom.css"]
  # customSCSS = ["scss/custom.scss"]
  # customJS = ["js/custom.js"]

# [taxonomies]
  # category = "categories"
  # series = "series"
  # tag = "tags"
  # author = "authors"

# Social links
[[params.social]]
  name = "Github"
  icon = "fa fa-github fa-2x"
  weight = 1
  url = "https://github.com/Tolledo/"
[[params.social]]
  name = "LinkedIn"
  icon = "fa fa-linkedin fa-2x"
  weight = 2
  url = "https://www.linkedin.com/in/constantine-gerasimovich/"
[[params.social]]
  name = "Twitter"
  icon = "fa fa-twitter fa-2x"
  weight = 3
  url = "https://twitter.com/magictolledo/"

# # Menu links
# [[menu.main]]
#   name = "Blog"
#   weight = 1
#   url  = "posts/"
# [[menu.main]]
#   name = "About"
#   weight = 2
#   url = "about/"